name: BusTracking_App
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  equatable: ^2.0.3
  flutter_map: ^0.14.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  http: ^0.13.4
  image_cropper: ^1.3.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  latlong2: ^0.8.1
  # location: ^3.2.4
  provider: ^6.0.2
  permission_handler: ^8.3.0
  share: ^2.0.4
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  socket_io_client: ^1.0.2
  stacked: ^2.2.7+1
  geolocator: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  stacked_generator: ^0.5.6
  stacked_services: ^0.8.16

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
